### ISSUE TITLE
缺少包文件

### ISSUE THREAD

**Issue by LYOfficial** [ClassToolsOfficial/ClassTools#11]
Hi，我想对ClassTools做出一点贡献，可是当我尝试用electron运行code时，总是提示我scripts文件夹的watch.mjs 中import的vite没有包文件，请问该如何解决？

**Comment by Clansty** [comment]
你运行 yarn 安装依赖了吗
有截图吗

**Comment by LYOfficial** [comment]
![rt](https://user-images.githubusercontent.com/79127081/205410474-300bb5e2-8813-4f9d-a021-c8833b89728f.png)
如图所示，我直接npm run dev了

**Comment by Clansty** [comment]
你需要使用 yarn 包管理器，先 yarn install
