### ISSUE TITLE
[Bug] 显示无法退出的一个白色屏幕

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [ClassToolsOfficial/ClassTools#5]
## 问题
ClassTools 运行后，显示一个白色屏幕，带天气预报和倒计时。除此之外无任何其他选项，也不能退出。

## 复现方式
运行即可

调整为最佳仍然不能解决

## 期望结果
- 显示完整的用户界面
- 给出一种退出的方式

## 环境
希沃大屏，Windows 10 系统，Portable 版本。

---
暂时 Close 直到我明天再试验一次留下截图为止。

---
Reopen，将之前 issue 里的讨论移到这里，如果需要会改标题

**Comment by Ravenclaw-OIer** [comment]
@Clansty 一打开就强制全屏了（

**Comment by Clansty** [comment]
![image](https://user-images.githubusercontent.com/18461360/167149609-35bf970c-2176-489c-8b1f-4d34d35eb5b5.png)

试试把这里调整为最佳外观，然后再试一次

**Comment by Ravenclaw-OIer** [comment]
调整为最佳外观仍然不行

**Comment by Clansty** [comment]
可以看一下 winver 的对话框嘛

**Comment by Ravenclaw-OIer** [comment]
![捕获](https://user-images.githubusercontent.com/44526586/167250642-7b074a11-b901-400d-ad22-006f56381b17.PNG)

**Comment by Clansty** [comment]
1703 我记得是可以的QAQ

**Comment by Ravenclaw-OIer** [comment]
是否可能是希沃做了限制啊（

**Comment by Clansty** [comment]
不太可能

**Comment by Clansty** [comment]
想知道这个问题现在解决了嘛QAQ

@Ravenclaw-OIer

**Comment by Ravenclaw-OIer** [comment]
> 想知道这个问题现在解决了嘛QAQ
> 
> @Ravenclaw-OIer

3.0.3 does not work

**Comment by Clansty** [comment]
试试最新的版本

@Ravenclaw-OIer

**Comment by Ravenclaw-OIer** [comment]
On Thursday, June 23, 2022 10:31:03 PM CST RainbowBird wrote:
> Closed #5 as completed.
我最近要期末考试所以没时间测试。考完之后我会拿最新版本测试一下，如果还有问题我就 reopen

-- 
From LilyWhite with love
